//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleProgrammer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration> Administration { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<User_registration> User_registration { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Test_results> Test_results { get; set; }
    }
}
